// <auto-generated />

namespace NoBright.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance =
            ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default => defaultInstance;
    }
}
